version: '0.2'
phases: 
    install: 
        runtime-versions:
            nodejs: 10
        commands: 
            - 'echo "--------INSTALL PHASE--------"'
            - 'pip3 install aws-sam-cli'
    pre_build: 
        commands: 
            - 'echo "--------PREBUILD PHASE--------"'
            - 'mkdir build'
            - '# Example shows installation of NPM dependencies for shared deps (layers) in a SAM App'
            - '# cd functions/dependencies/shared_deps_one/nodejs'
            - '# npm install && cd'
            - '# cd functions/dependencies/shared_deps_two/nodejs'
            - '# npm install && cd'
    build:
        commands:
            - 'echo "--------BUILD PHASE--------"'
            - 'cd sam-app'
            - 'echo "Starting SAM packaging `date` in `pwd`"'
            - 'sam package --template-file template.yaml --s3-bucket $BUILD_ARTIFACT_BUCKET --output-template-file ../build/packaged.yaml'
    post_build:
        commands:
            - 'echo "--------POST-BUILD PHASE--------"'
            - 'echo "SAM packaging completed on `date`"'
artifacts:
    files: 
        - 'build/packaged.yaml'
    discard-paths: 'yes'
cache:
    paths:
        - '/root/.cache/pip'
